import os
import json
from typing import List, Dict, Any
from fastapi import APIRouter, Depends, status, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession
from database.session import get_db
from models.user import User
from routes.auth_routes import get_current_user
from services.project_service import ProjectService

router = APIRouter(prefix="/api/project", tags=["Projects"])

@router.post(
    "/analyze",
    status_code=status.HTTP_201_CREATED,
    summary="Analyze project requirement constraints and generate recommendations",
)
async def analyze_project(
    data: Dict[str, Any],
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Submits project requirements form payload, records constraints, and triggers AI recommendation.
    """
    try:
        recommendation = await ProjectService.analyze_project_requirements(db, current_user.id, data)
        return {
            "message": "Analysis completed successfully.",
            "project_id": recommendation.project_id,
            "recommendation_id": recommendation.id
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred during analysis: {str(e)}"
        )

@router.get(
    "/history",
    status_code=status.HTTP_200_OK,
    summary="Retrieve user architectural recommendation history list",
)
async def get_history(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Returns index records of previous recommendations generated by active user.
    """
    history = await ProjectService.get_user_projects_history(db, current_user.id)
    return history

@router.get(
    "/{id}",
    status_code=status.HTTP_200_OK,
    summary="Retrieve project requirements and generated recommendation mapping",
)
async def get_project_details(
    id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Queries database and returns user requirement fields plus complete AI analysis payload.
    """
    project = await ProjectService.get_project_by_id(db, id, current_user.id)
    rec = await ProjectService.get_recommendation_by_project(db, id, current_user.id)
    
    return {
        "project": {
            "id": project.id,
            "name": project.name,
            "description": project.description,
            "domain": project.domain,
            "expected_users": project.expected_users,
            "budget": project.budget,
            "deadline": project.deadline,
            "team_size": project.team_size,
            "target_platform": project.target_platform,
            "required_features": project.required_features,
            "security_level": project.security_level,
            "scalability": project.scalability,
            "availability": project.availability,
            "preferred_cloud": project.preferred_cloud,
            "expected_traffic": project.expected_traffic,
            "third_party_integrations": project.third_party_integrations,
            "created_at": project.created_at.isoformat()
        },
        "recommendation": {
            "id": rec.id,
            "architecture_pattern": rec.architecture_pattern,
            "frontend_tech": rec.frontend_tech,
            "backend_tech": rec.backend_tech,
            "database_tech": rec.database_tech,
            "auth_tech": rec.auth_tech,
            "cloud_platform": rec.cloud_platform,
            "deployment_strategy": rec.deployment_strategy,
            "devops_tools": rec.devops_tools,
            "cicd_pipeline": rec.cicd_pipeline,
            "comparison_data": json.loads(rec.comparison_data),
            "cost_estimation_data": json.loads(rec.cost_estimation_data),
            "timeline_data": json.loads(rec.timeline_data),
            "sprint_plan_data": json.loads(rec.sprint_plan_data),
            "risk_analysis_data": json.loads(rec.risk_analysis_data),
            "diagram_mermaid": rec.diagram_mermaid,
            "summary": rec.summary,
            "created_at": rec.created_at.isoformat()
        }
    }

@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete project history and all nested blueprints",
)
async def delete_project(
    id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Removes project requirements and cascades clearance to recommendations.
    """
    await ProjectService.delete_project(db, id, current_user.id)

@router.get(
    "/{id}/pdf",
    status_code=status.HTTP_200_OK,
    summary="Download executive PDF recommendation report",
)
async def download_pdf(
    id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generates and returns PDF report as attachment.
    """
    filepath = await ProjectService.export_pdf_report(db, id, current_user.id)
    if not os.path.exists(filepath):
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Failed to generate document."
        )
    return FileResponse(
        path=filepath,
        media_type="application/pdf",
        filename=os.path.basename(filepath)
    )
